Update mongo-backup.yml

diff --git a/.github/workflows/mongo-backup.yml b/.github/workflows/mongo-backup.yml
--- a/.github/workflows/mongo-backup.yml
+++ b/.github/workflows/mongo-backup.yml
@@ -38,15 +38,19 @@ jobs:
           sudo apt-get install -y mailutils msmtp-mta
 
       - name: Verificar variables de entorno
+        env:
+          EMAIL_TO: ${{ secrets.EMAIL_TO }}
+          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
         run: |
           if [ -z "$EMAIL_TO" ]; then
-          echo "ERROR: EMAIL_TO no está configurado."
-          exit 1
+            echo "ERROR: EMAIL_TO no está configurado."
+            exit 1
           fi
           if [ -z "$EMAIL_FROM" ]; then
-          echo "ERROR: EMAIL_FROM no está configurado."
-          exit 1
+            echo "ERROR: EMAIL_FROM no está configurado."
+            exit 1
           fi
+
 
       
 
